[package]
name = "rotom-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.ntex]
version = "2.13.2"
default-features = false
features = ["tokio"]

[dependencies.sqlx]
version = "0.8.5"
features = ["postgres", "runtime-tokio", "uuid"]
